services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\ModuleTemplate\Logging\Command\ReadLogsCommand:
    class: OxidEsales\ModuleTemplate\Logging\Command\ReadLogsCommand
    arguments:
      $logFilePath: '%app.log_file_path%'
    tags:
      - { name: 'console.command', command: 'oetemplate:logger:read' }

  OxidEsales\ModuleTemplate\Logging\Service\BasketItemLogger:
    class: OxidEsales\ModuleTemplate\Logging\Service\BasketItemLogger
    public: true
    arguments:
      $logger: '@OxidEsales\ModuleTemplate\Logger'

  OxidEsales\ModuleTemplate\Logger:
    class: Monolog\Logger
    factory: [ '@OxidEsales\ModuleTemplate\Logger\Factory', 'create' ]

  OxidEsales\ModuleTemplate\Logger\Factory:
    class: OxidEsales\EshopCommunity\Internal\Framework\Logger\Factory\MonologLoggerFactory
    arguments:
      $configuration: '@OxidEsales\ModuleTemplate\Logger\Configuration'

  OxidEsales\ModuleTemplate\Logger\Configuration:
    class: OxidEsales\EshopCommunity\Internal\Framework\Logger\Configuration\MonologConfiguration
    arguments:
      $loggerName: 'Basket Logger'
      $logFilePath: '%app.log_file_path%'
      $logLevel: !php/const Psr\Log\LogLevel::DEBUG