services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\ModuleTemplate\Command\ReadLogsCommand:
    class: OxidEsales\ModuleTemplate\Command\ReadLogsCommand
    arguments:
      $logFilePath: '%app.log_file_path%'
    tags:
      - { name: 'console.command', command: 'oetemplate:logger:read' }