# {{ $ids := "oe_moduletemplate" }}ids: {{ $ids }}
# {{ $org := "oxid-esales" }}organisation: {{ $org }}
# {{ $name := "module-template" }}name: {{ $name }}
# {{ $repo := "OXID-eSales/module-template" }}repo: {{ $repo }}

install_shop_with_modules:
  cache:
    prepared_shop: false
  composer:
    transform: |
      {
          "preferred-install": {
            "oxid-esales/*": "source",
            "oxid-professional-services/*": "source",
            "ddoe/*": "source"
          },
          "require": {
              "oxid-esales/oxideshop-ce": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-component": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-admin-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/apex-theme": "{{ .Data.global.composer.dev_ref }}",
              "{{ $org }}/{{ $name }}": "dev-{{ .Github.RefName }}"
          },
          "repositories": {
            "{{ $org }}/{{ $name }}": {
              "type": "git",
              "url": "https://github.com/{{ $repo }}.git"
            }
          }
      }
  custom_script_container: |
    vendor/bin/oe-console oe:module:activate "{{ $ids }}"

runscript: &runscript
  matrix:
    script: |
      [
        "module_template:tests-unit",
        "module_template:tests-integration",
        "module_template:tests-codeception"
      ]
  module_template:
    path: 'vendor/{{ $org}}/{{ $name }}'

runslim:
  <<: *runscript
  matrix:
    script: |
      [
        "module_template:phpcs-report",
        "module_template:phpmd-report",
        "module_template:phpstan-report"
      ]

sonarcloud:
  matrix:
    testplan: '["-"]'
  strip_path: '/var/www/vendor/{{ print $org }}/{{ print $name}}/'
  project_key: 'OXID-eSales_{{ print $name }}'
  project_name: '{{ $org}}/{{ $name }}'
  parameters: |
    -Dsonar.language=php
    -Dsonar.scm.provider=git
    -Dsonar.sources=src
    -Dsonar.tests=tests
    -Donar.php.phpstan.reportPaths=coverage-reports/phpstan.report.json

finish:
  slack_title: '{{ print $name }} ({{ .Data.global.git.shop_ref }}) by {{ .Github.Actor }}'
