install:
  cache:
    prepared_shop: false
  composer:
    root_url: ''
    transform: |
      {
        "require": {
          "oxid-esales/apex-theme": "{{ .Data.install.composer.dev_ref }}",
          "oxid-esales/oxideshop-ce": "{{ .Data.install.composer.dev_ref }}",
          "oxid-esales/twig-admin-theme": "{{ .Data.install.composer.dev_ref }}",
          "oxid-esales/twig-component": "{{ .Data.install.composer.dev_ref }}"
        }
      }
  custom_script_container: |
    vendor/bin/oe-console oe:database:reset --db-host=mysql --db-port=3306 --db-name=example --db-user=root --db-password=root --force
    vendor/bin/oe-console oe:module:install ./
    vendor/bin/oe-eshop-doctrine_migration migrations:migrate
    vendor/bin/oe-console oe:module:activate oe_moduletemplate
    vendor/bin/oe-console oe:theme:activate apex

runscript: &runscript
  matrix:
    script: |
      [
        "report:tests-unit",
        "report:tests-integration",
        "no_report:tests-codeception",
      ]
  report:
    path: ''
  no_report:
    path: ''
    coverage_prefix: ''

runslim:
  <<: *runscript
  matrix:
    script: |
      [
        "report:phpstan-report",
        "no_report:phpmd-report",
        "no_report:phpcs-report",
      ]

sonarcloud:
  matrix:
    testplan: '["-"]'
  strip_path: '/var/www/'
  organization: 'oxid-esales'
  project_name: 'oxid-esales/module-template'
  project_key: 'OXID-eSales_module-template'
  target_branch: 'b-7.3.x'
  parameters: >
    -Dsonar.language=php
    -Dsonar.scm.provider=git
    -Dsonar.sources=src
    -Dsonar.tests=tests

finish:
  slack_title: 'Module template ({{ .Data.install.git.ref }}) by {{ .Github.Actor }}'
