# {{ $ids := "oe_moduletemplate" }}ids: {{ $ids }}
# {{ $org := "oxid-esales" }}organisation: {{ $org }}
# {{ $name := "module-template" }}name: {{ $name }}
# {{ $repo := "OXID-eSales/module-template" }}repo: {{ $repo }}

install_shop_with_modules:
  cache:
    prepared_shop: false
  composer:
    transform: |
      {
          "preferred-install": {
            "oxid-esales/*": "source",
            "oxid-professional-services/*": "source",
            "ddoe/*": "source"
          },
          "require": {
              "oxid-esales/oxideshop-ce": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-component": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-admin-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/apex-theme": "{{ .Data.global.composer.dev_ref }}",
              "{{ $org }}/{{ $name }}": "dev-{{ .Github.RefName }}",
              "codeception/codeception": "^5.0",
              "codeception/module-asserts": "^3.0",
              "codeception/module-db": "^3.0",
              "codeception/module-filesystem": "^3.0",
              "codeception/module-webdriver": "^3.1",
          },
          "repositories": {
            "{{ $org }}/{{ $name }}": {
              "type": "git",
              "url": "https://github.com/{{ $repo }}.git"
            }
          }
      }
  custom_script_container: |
    OE_CONSOLE=$(find . -iname "oe-console" -type f|head -1|sed -e "s|^$(pwd)/||")
    ${OE_CONSOLE} oe:module:activate "{{ $ids }}"

runscript:
  matrix:
    script: |
      [
        "module_template:tests-unit",
        "module_template:tests-integration",
        "module_template:tests-codeception",
        "module_template:phpcs-report",
        "module_template:phpmd-report",
        "module_template:phpstan-report"
      ]
  module_template:
    path: 'vendor/{{ $org}}/{{ $name }}'

sonarcloud:
  matrix:
    testplan: 'skip'
    # testplan: '["-"]'
  strip_path: '/var/www/vendor/{{ print $org }}/{{ print $name}}/'
  project_key: 'OXID-eSales_{{ print $name }}'
  project_name: '{{ $org}}/{{ $name }}'
  parameters: |
    -Dsonar.language=php
    -Dsonar.scm.provider=git
    -Dsonar.sources=src
    -Dsonar.tests=tests

finish:
  slack_title: '{{ print $name }} ({{ .Data.global.git.shop_ref }}) by {{ .Github.Actor }}'
