# {{ $org := "oxid-esales" }}organisation: {{ $org }}
# {{ $name := "module-template" }}name: {{ $name }}
# {{ $repo := "OXID-eSales/module-template" }}repo: {{ $repo }}

install_shop_with_modules:
  git:
    shop_ref: '{{ .Data.global.git.default_ref }}'
  composer:
    transform: |
      {
          "preferred-install": {
            "oxid-esales/*": "source",
            "oxid-professional-services/*": "source",
            "ddoe/*": "source"
          },
          "require": {
              "oxid-esales/twig-component": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-admin-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/apex-theme": "{{ .Data.global.composer.dev_ref }}",
              "{{ $org }}/{{ $name }}": "dev-{{ .Github.RefName }}"
          },
          "repositories": {
            "{{ $org }}/{{ $name }}": {
              "type": "git",
              "url": "https://github.com/{{ $repo }}.git"
            }
          }
      }

runscript:
  matrix:
    script: |
      [
        "tests-unit",
        "tests-integration",
        "tests-codeception",
        "phpcs-report",
        "phpmd-report",
        "phpstan-report"
      ]
  path: 'vendor/{{ $org}}/{{ $name }}'

sonarcloud:
  matrix:
    testplan: 'skip'
    # testplan: '["-"]'
  strip_path: '/var/www/vendor/{{ print $org }}/{{ print $name}}/'
  project_key: 'OXID-eSales_{{ print $name }}'
  project_name: '{{ $org}}/{{ $name }}'
  parameters: |
    -Dsonar.language=php
    -Dsonar.scm.provider=git
    -Dsonar.sources=src
    -Dsonar.tests=tests

finish:
  slack_title: '{{ print $name }} ({{ .Data.global.git.shop_ref }}) by {{ .Github.Actor }}'
