name: Auto trigger on Push to 7.1.x*

on:
  push:

jobs:
  p80m57both:
    name: 'Php-8.0-Mysql-5.7'
    uses: ./.github/workflows/development.yml
    secrets: inherit
    with:
      php: '8.1'
      mysql: '5.7.37'
      report_sonarcloud: true
