name: Schedule for module template actions

on:
  schedule:
    - cron: '0 0 */7 * *'

jobs:
  call_full_matrix:
    uses: oxid-eSales/github-actions/.github/workflows/call-test_matrix.yml@v3
    with:
      testplan: 'https://raw.githubusercontent.com/OXID-eSales/github-actions/v2/testplans/modules/oe_moduletemplate.yml'
      runs_on: '"ubuntu-latest"'
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      CACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
      CACHE_ACCESS_KEY: ${{ secrets.CACHE_ACCESS_KEY }}
      CACHE_SECRET_KEY: ${{ secrets.CACHE_SECRET_KEY }}
      enterprise_github_token: ${{ secrets.enterprise_github_token }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  p80m57both:
    name: 'Php-8.0-Mysql-5.7'
    uses: ./.github/workflows/development.yml
    secrets: inherit
    with:
      php: '8.0'
      mysql: '5.7.37'