name: Auto trigger on push or pull requests

on:
  pull_request: {}
  push:
    branches:
      - 'b-7.3.x**'

jobs:
  php82_mysql80:
    uses: oxid-eSales/github-actions/.github/workflows/universal_workflow_light.yaml@v5
    with:
      testplan: '~/defaults/7.3.x.yaml,~/defaults/php8.2_mysql8.0_only.yaml,~/module-template.yaml,~/_custom.yaml'
      runs_on: '"ubuntu-latest"'
      defaults: 'v5'
      plan_folder: '.github/oxid-esales'
      custom_testplan_yaml: |
        finish:
          slack_title: 'PHP82-MySQL80-{{ .Github.EventName }}-{{ .Github.RefName }}'
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      CACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
      CACHE_ACCESS_KEY: ${{ secrets.CACHE_ACCESS_KEY }}
      CACHE_SECRET_KEY: ${{ secrets.CACHE_SECRET_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
